language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
before_script:
    - mysql -e 'create database konwent;'
    - mysql -u root konwent < konwent.sql
    - mysqldump -u root konwent
script: phpunit --coverage-text tests/
